# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Electronic Studio Methods and Composition  
email: Louis.Goldford@mh-luebeck.de  
description: >- # this means to ignore newlines until "baseurl:"
  Winter 2024—2025 | Tuesdays 10:00—11:30 | Electronic Music Studio    
twitter_username: einbahnstrasse  
github_username: einbahnstrasse  
minimal_mistakes_skin: sunrise   
search: true
lunr:  
  search_within_pages: true   

# baseurl: MHL-studio-methods

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  # - jekyll-toc  

author:
  name   : "Louis Goldford"
  avatar : "/assets/images/Goldford.square.sm.jpg"
  bio    : "composer"
  links:
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://louisgoldford.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/einbahnstrasse"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/einbahnstrasse"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/louis.goldford"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/einbahnstrasse"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/einbahnstrasse"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/louis.goldford"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      # words_per_minute: 200
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  # toc_levels: 1..6
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Schedule-specific variables   

weekly-deadline-statement: Unless otherwise noted, assignments are always due online on GitHub at 11:59 PM the following Monday night each week!
MHL-calendar: https://www.mh-luebeck.de/studium/termine-und-fristen/

week-01: 1 Oct.       
week-02: 8 Oct.            
week-03: 15 Oct.            
week-04: 22 Oct.            
week-05: 29 Oct.            
week-06: 5 Nov.  
week-07: 12 Nov.  
week-08: 19 Nov.  
week-09: 26 Nov.  
week-10: 3 Dec.  
week-11: 10 Dec.  
week-12: 17 Dec.  
week-13: 7 Jan.  
week-14: 14 Jan.  
week-15: 21 Jan.  
week-16: 28 Jan.  
week-17: 4 Feb.  
week-18: 11 Feb.  

week-01-topic: What is Sound?   
week-02-topic: Introduction to Reaper/Ableton Live           
week-03-topic: Introduction to Modular Synthesis in VCV Rack            
week-04-topic: Reaper/Ableton Plugins and Automation          
week-05-topic: Basic Soundfile Treatments     
week-06-topic: No Synchronous Class     
week-07-topic: Reaper/Ableton Sampling and MIDI Controllers        
week-08-topic: Mixing and Audio Post Production      
week-09-topic: Multichannel Spatial Audio             
week-10-topic: Introduction to MaxMSP             
week-11-topic: Frequency Domain Editing with SPEAR              
week-12-topic: Workshop Session on Pieces    
week-13-topic: No Synchronous Class       
week-14-topic: MaxMSP Filters + Time Domain Treatments           
week-15-topic: TBA...         
week-16-topic: Modular Synthesis (Part 2) in VCV Rack      
week-17-topic: TBA...     
week-18-topic: TBA...   

# language plugin settings   

languages: ["en", "sv", "de", "fr"]  
default_lang: "en"  
exclude_from_localization: ["javascript", "images", "css", "public"]  
parallel_localization: true  
